# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6af69808ded95e8c40c90582cf25dcc2ba34302df37e785aadd46e9f04d652ec22a35b387a05572cb0dd12e2e0bee25948449d4a146aa0c896393985be62cf16

test:
  secret_key_base: 76497fce5563d45edc6932ce8785424f08fc7775761770b28ddc77f2e2dc496737473fefdab783f2a16c80ba076f4f8eecf0ef050ea359be339131843990127b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
